# shellcheck shell=bash
#
# radare2/mayhem/subprojects-cache.sh -- SOURCED by mayhem/build.sh (defines sprj_cache_setup).
#
# radare2's git subprojects (sdb, qjs, otezip, capstone-v5, ...) are fetched by the upstream,
# acr-wrap-autogenerated subprojects/<name>.mk recipes:
#
#   git clone --no-checkout --depth=1 <url> <name>; cd <name> && git fetch --depth=1 origin <rev>;
#   git checkout FETCH_HEAD; [cp -rf packagefiles/...]; [patch ...]
#
# and every subprojects/<name> checkout is .gitignore'd. So the grader's `git clean -ffdX` deletes
# them, and the air-gapped graded rebuild would have to re-clone them from github.com.
#
# This applies the SPEC 6.5 two-knob principle to those clones, without touching an upstream file:
#   (1) populate: for every git subproject this configuration builds, keep a bare mirror under
#       $R2_SUBPROJECTS_CACHE (/opt/toolchains/..., outside the source tree, so `git clean` never sees
#       it) that holds the exact url+revision the .mk pins. The fetch happens only on a cache miss,
#       which means the first, online image build or the first build after an upstream pin bump.
#   (2) prefer: export `url.file://<mirror>.insteadOf=<url>` (GIT_CONFIG_COUNT env, which only
#       applies to build.sh's own process tree). The UNMODIFIED .mk recipe then clones from the
#       mirror, with no network, and the result is the same checkout: same commit SHA, origin
#       still <url>, and the same packagefiles/patch steps run by the .mk itself.
#
# Nothing here is fatal. A cache miss that cannot be filled (offline, or the cache dir isn't
# writable) only prints a warning and leaves that URL un-rewritten, so the .mk behaves exactly as
# upstream does. A pin bump from an upstream sync re-populates on the next online build by itself.

# mkvar <file.mk> <key>: WRAP_wrap_git_<key> from an acr-wrap .mk ("" if absent).
_sprj_mkvar() { awk -v k="WRAP_wrap_git_$2:=" 'index($0, k) == 1 { print substr($0, length(k) + 1); exit }' "$1"; }

# _sprj_has <mirror> <rev>: does the mirror already hold the pinned revision?
_sprj_has() { git -C "$1" rev-parse -q --verify "refs/mayhem-pins/$2^{commit}" >/dev/null 2>&1; }

# _sprj_fetch <mirror> <url> <rev>: fetch <rev> exactly as the .mk does (--depth=1, by tag or SHA)
# and pin it with refs the .mk's later `git fetch origin <rev>` will resolve against the mirror.
_sprj_fetch() {
  local m="$1" url="$2" rev="$3"
  if [ ! -d "$m" ]; then
    git init -q --bare "$m" || return 1
  fi
  # A .mk `git fetch --depth=1 origin <sha>` asks for a bare SHA.
  git -C "$m" config uploadpack.allowAnySHA1InWant true || return 1
  git -C "$m" config gc.auto 0 || return 1
  git -C "$m" fetch -q --no-tags --depth=1 "$url" "$rev" || return 1
  git -C "$m" update-ref "refs/mayhem-pins/$rev" FETCH_HEAD || return 1
  # A tag/branch pin: the .mk fetches it BY NAME, so publish it under that name (refs/tags/ is
  # matched by `git fetch origin <name>`'s DWIM). Points at what upstream's ref points at (FETCH_HEAD).
  if ! printf '%s' "$rev" | grep -qE '^[0-9a-f]{40}$'; then
    git -C "$m" update-ref "refs/tags/$rev" FETCH_HEAD || return 1
  fi
  # Give the `git clone --depth=1` a non-empty default branch, as github does (it is replaced by
  # the later `fetch origin <rev>` + `checkout FETCH_HEAD`).
  git -C "$m" update-ref refs/heads/main "refs/mayhem-pins/$rev^{commit}" || return 1
  git -C "$m" symbolic-ref HEAD refs/heads/main
}

# sprj_cache_setup <subprojects-dir> <cache-dir> <dep>...: populate + export the url rewrites.
sprj_cache_setup() {
  local sprj="$1" cache="$2"; shift 2
  if ! mkdir -p "$cache" 2>/dev/null || [ ! -w "$cache" ]; then
    echo "mayhem: WARNING: subproject cache $cache is not writable; subprojects/*.mk will clone from" \
         "the network, as upstream does (so the air-gapped rebuild of a git-clean'ed tree cannot work)" >&2
    return 0
  fi
  local name mk url rev m rw=()
  for name in "$@"; do
    mk="$sprj/$name.mk"
    [ -f "$mk" ] || continue
    url="$(_sprj_mkvar "$mk" url)"; rev="$(_sprj_mkvar "$mk" revision)"
    [ -n "$url" ] && [ -n "$rev" ] || continue          # not a git wrap (e.g. zydis: tracked files)
    m="$cache/$(printf '%s' "${url#*://}" | tr -c 'A-Za-z0-9._/-' '_')"
    if _sprj_has "$m" "$rev"; then
      echo "mayhem: subproject $name: $url @ $rev <- $m (cached)"
    elif _sprj_fetch "$m" "$url" "$rev" && _sprj_has "$m" "$rev"; then
      echo "mayhem: subproject $name: $url @ $rev -> cached in $m"
    else
      echo "mayhem: WARNING: subproject $name: $url @ $rev is not cached and could not be fetched;" \
           "leaving subprojects/$name.mk to clone it from the network" >&2
      continue
    fi
    rw+=("$m" "$url")
  done
  # Export only after every fetch, so populating one mirror never goes through another's rewrite
  # (capstone-v4/-v5/-next share one URL).
  local n="${GIT_CONFIG_COUNT:-0}" i
  for ((i = 0; i < ${#rw[@]}; i += 2)); do
    export "GIT_CONFIG_KEY_$n=url.file://${rw[i]}.insteadOf" "GIT_CONFIG_VALUE_$n=${rw[i+1]}"
    n=$((n + 1))
    # The graded rebuild may run under a uid other than the one that populated the cache.
    export "GIT_CONFIG_KEY_$n=safe.directory" "GIT_CONFIG_VALUE_$n=${rw[i]}"
    n=$((n + 1))
  done
  export GIT_CONFIG_COUNT="$n"
}
